### ISSUE TITLE
watch new quests now only works for dailies

### ISSUE THREAD

**Issue by wownob** [Rythal/Carbonite#343]
I use the latest dev version. Now daily quests are put to the watch window but normal quests don't.
Happens in Elvyn, Westfall, Redridge (new character).

**Comment by IrcDirk** [comment]
No logs no help.

**Comment by IrcDirk** [comment]
No logs no help.

**Comment by wownob** [comment]
Starting with quests of lvl 21 the quests were autowatched again.
So the problem seems to appear with low lvl chars only.
If any additional Information is needed please tell me what is desired.
An error log is not available, since there was no lua error.

**Comment by JWMcQuire** [comment]
I am presently using the latest build of the Dev version.

I am also leveling alts for my guild's *Stay Classy* achievement. So I have done the low level quests multiple times and have only experienced this issue a few times on random low level quests, but not on the same level you indicate. So I suggest you try removing Carbonite completely, download it again to ensure you have the latest update of the dev version, and reinstall it. Since the *saved variable's* folder is in your wtf folder, your settings should not be affected by this. What this will do, is give you a fresh install which may (or may not) correct this issue or reduce the instances it will come up. This has fixed some issues for my guild mates who usually just do an overwrite update instead of removing the old and installing the new. If you don't mind redoing your settings, you can remove Carbonite's related files from the *saved variable's* folder in the wtf folder for a completely new reinstall.

As far as logs go, just post a list of the mods you have installed besides Carbonite. This will give Rythal and team a chance to see if the issue may be related to a conflict that doesn't cause lua errors. Also, a screenshot may help to give an idea of what your issue looks like in-game.

Finally, and with apologies for such a long reply, see if reloading your UI will fix your issue. In some cases a quest will show up in the watch window, but as "not in database". This is often fixed with a UI reload.

I hope this helps. Good luck.

**Comment by wownob** [comment]
So I got the reason for my problem:
Before starting my new char a had have a char with the same name on the same Server and the same race which I deleted.
This deletion was not reflected in Carbonite's WTF files.
After starting my new char Carbontie assumed a lot of quests already been done.
As consequence it didn't auto watch these quests.
