### ISSUE TITLE
Map Icons not showing in Orgrimmar

### ISSUE THREAD

**Issue by LustSinister** [Rythal/Carbonite#438]
I know there are two different size maps the pictures I will be showing are the when the world map is open. With that said this happens on both sized maps and I have messed around with all settings. Also did a reset to make sure it wasn't something I messed up. So basically when I was first on the map it looked like there were no icons for the city area. but then I moved my mouse the city drawn map dissappeared and boom icons were underneath. 

![first](https://cloud.githubusercontent.com/assets/16523313/17466171/99bbbaf6-5cd7-11e6-8c64-1e74937608f0.png)

![second](https://cloud.githubusercontent.com/assets/16523313/17466173/b7ff43de-5cd7-11e6-8e82-cfa401ecfb42.png)

**Comment by IrcDirk** [comment]
For me location of icons is ok but the strata of them is wrong, they are behind ogrimar map.

**Comment by jeffy162** [comment]
I'm not sure if this will help, but, go to your Carbonite options. On the Maps page "Minimap Options" tab, make sure that you have the "Minimap is drawn above icons" option UNchecked. That _**SHOULD**_ be unchecked by default, but it's been a l o n g time since i actually checked that option to see if it was checked or not. (_checked checked checked.........._)

**Comment by IrcDirk** [comment]
Sorry but that doesnt help.

**Comment by LustSinister** [comment]
Same that didn't work for me as well.

**Comment by IrcDirk** [comment]
After yesterday fixes this is still wrong, icons are under ogrimmar map.

**Comment by jeffy162** [comment]
Well, I did say that I wasn't sure if it would help. I finally got to Orgrimmar and, yeah, the icons _**are there**_, but, unfortunately **they are under the map**. I tried my own advice and it didn't work for me either. What is strange is that Orgrimmar is the only place this happens at (as far as I can tell).

**Comment by IrcDirk** [comment]
I have tried to find why this happens but no luck...

**Comment by jeffy162** [comment]
Yeah, it's probably some Blizzard mess up that they're not telling anyone about, BUT, this _**IS**_ pre-expansion so they don't have all the kinks worked out yet.

Installed a new Carbonite yesterday, and it is still happening.
![2016-08-12](https://cloud.githubusercontent.com/assets/8658862/17643469/161525be-6139-11e6-938a-8d11679d62bb.png)
![2016-08-12](https://cloud.githubusercontent.com/assets/8658862/17643470/18f40e80-6139-11e6-8981-9334b86a01a0.png)

**Comment by Rythal** [comment]
Issue fixed, the cause was the code added last expansion to support dungeon levels / microdungeons... for some reason Ogrimmar reports itself as DungeonLevel 1 now, and icons are not to draw on the map if they are not dungeon level 0... installed work around that changes the dungeon level to 0 just during icon drawing then back to 1 so nothing else gets affected.
